### ISSUE TITLE
Use invisible unicode characters as prefixes to title

### ISSUE THREAD

**Issue by jacksongoode** [Naezr/userchrome-toggle-extended-2#1]
https://invisible-characters.com/

**Comment by Naezr** [comment]
Thank you so much for this website. I removed the invisible characters used in the original Userchrome Toggle, as there were only three, and one of them did not display well in the Browser Toolbox. On this site I found 6 characters that Browser Toolbox displays correctly.

![image](https://github.com/user-attachments/assets/9c48b583-d8c4-4c40-9b41-4210513bd42c)
> how symbols looks in Browser Toolbox

I will have to adapt ShyFox to the new characters, and there are more important things to do in the development of this extension, but I will add it anyway

**Comment by jacksongoode** [comment]
Woohoo!

**Comment by ZaheenJ** [comment]
All of the invisible characters are working perfectly for me except \u61c. For some reason, it forces my waybar to increase its height. I don't know if this is my font's (Iosevka Nerd Font) or waybar's fault but it might be worth considering using a different character.

Normal Height:
![image](https://github.com/user-attachments/assets/d6823892-7fc8-4b81-bf42-e71cb343271a)

Expanded Height because of \u61c:
![image](https://github.com/user-attachments/assets/e607b1ba-51c3-4004-aaeb-6d88070226c9)

Userchrome Toggle Extended settings:
![image](https://github.com/user-attachments/assets/2f0c228e-a5c8-4a41-b93b-db28a2ece34f)

**Comment by Naezr** [comment]
> it might be worth considering using a different character.

I definitely don't want to change the characters in the extension and update ShyFox under that again. I already broke everything with this update, so people have to update. I don't want to have to do it again the next day. Is there any way to force the Waybar height or something?

**Comment by jacksongoode** [comment]
I think this is definitely a font related thing. Maybe your custom font doesn't set the proper height for that invisible unicode char?
